name: devtools_plus
description: "DevTools+ — a modern collection of developer productivity utilities."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  liquid_swipe: ^3.1.0
  crypto: ^3.0.5
  uuid: ^4.5.1
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.2
  encrypt: ^5.0.3
  http: ^1.2.1
  diff_match_patch: ^0.4.1
  file_picker: ^6.1.1
  pdf: ^3.11.1
  printing: ^5.11.0
  reorderables: ^0.6.0
  path_provider: ^2.1.2
  path: ^1.9.0
  image: ^4.2.0
  archive: ^3.6.1
  yaml: ^3.1.2
  csv: ^5.1.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/


flutter_launcher_icons:
  android: false
  ios: false
  web:
    generate: false
  macos:
    generate: false
  linux:
    generate: false
  windows:
    generate: true
    image_path: assets/app_icon.png
