name: devtools_plus
description: "DevTools+ — a modern collection of developer productivity utilities."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  liquid_swipe: ^3.1.0
  glassmorphism: ^3.0.0
  crypto: ^3.0.3
  uuid: ^4.4.0
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.0
  file_picker: ^8.0.0+1
  pdf: ^3.10.8
  printing: ^5.11.1
  image: ^4.1.7
  flutter_image_compress: ^2.2.0
  yaml: ^3.1.2
  csv: ^6.0.0
  flutter_markdown: ^0.7.1
  hugeicons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/


flutter_launcher_icons:
  android: false
  ios: false
  web:
    generate: false
  macos:
    generate: false
  linux:
    generate: false
  windows:
    generate: true
    image_path: assets/app_icon.png
